### ISSUE TITLE
Conflict with Google Form Script Editor

### ISSUE THREAD

**Issue by schuelaw** [emichael/texthings#13]
Hi, Math prof here.  Love this extension.  Recommend it to all of my students.  Was working on a google form this morning.  When you're the owner of a google form and your editing it in the Chrome browser (Version 48.0.2564.103 m, Windows 10, 64 bit), there is a `Tools` menu.  This menu let's the author edit scripts that are associated with the form.  If you have "TeX All The Things" installed and active and in your form you attempt to open `Tools->Script Editor...` you get a file open error, (i.e. you can't get to the associated scripts).

The behavior seems pretty repeatable.  Of course, one workaround is to disable "TeX All The Things" when working with google forms, but I thought you might like to know.

Thanks again for a great extension!

Sincerely,

Albert Schueller

**Comment by emichael** [comment]
Hi @schuelaw, thanks for the bug report and for recommending the extension!

I'm getting the same issue. I'm not entirely sure what's going on, but it has something to do with the script editor expecting certain elements of the DOM to look a certain way, and when MathJax gets injected, those expectations aren't met. Unfortunately, this is probably Google Docs' fault, and since I don't control MathJax either, I can't do too much about it. For now, I would recommend blacklisting `script.google.com` in the extension options.

I'm actually surprised that none of the other extensions break the script editor.

**Comment by felipewos** [comment]
Boa noite!

Também sou professor de Matemática e estou tendo um problema com a extensão "tex all the things".
Ele funciona em todos os sites, mas não funcina no google forms.

Apresenta o seguinte probelma:

"Arquivo indisponível"
"Há um problema com o arquivo. Atualize.

Parabéns pela excelente extensão!!!
