### ISSUE TITLE
abnormally high CPU usage

### ISSUE THREAD

**Issue by zshihang** [emichael/texthings#23]
when check the box "Custom: \( \)" under inline math, texthings stops rendering and also eat all cpu.

here is the page I tried on "https://www.tensorflow.org/tutorials/word2vec"

**Comment by emichael** [comment]
My best guess is that because MathJax is already present on that site, trying to load it in is bad. I'll see what I can do, but in the meantime, I suggest leaving the extension on whitelist mode, which is what I do.

**Comment by pkra** [comment]
> My best guess is that because MathJax is already present on that site, trying to load it in is bad. 

MathJax checks if it has been loaded and shouldn't load a second time. So if you're right, please file a bug upstream.

**Comment by emichael** [comment]
@pkra Wow, that was fast. Thanks for the info. :-)

**Comment by emichael** [comment]
@shihan9 I think you just checked the custom boxes without actually putting anything into them. The light-grey text is a suggestion, not the default. It turns out that configuring MathJax with blank delimiters will cause it to thrash on any page, not just the example you gave.

Now I interpret blank custom delimiters as the default, greyed-out options. This should prevent anyone else from running into this.

**Comment by zshihang** [comment]
@emichael I thought that was default settings. thank you very much. it works pretty well now.

**Comment by pkra** [comment]
> It turns out that configuring MathJax with blank delimiters will cause it to thrash on any page, not just the example you gave.

I suspect what happens is that MathJax gets configured to use whitespace as math delimiters - which will definitely get wonky.
